name: Deploy to Kubernetes Cluster

# Triggers on new tag pushes
on:
  push:
    
      

jobs:
  # Builds a new container image based on the tag release
  build:
    name: Build
    runs-on: ubuntu-latest
   
    steps:
      - name: Checkout files    
        uses: actions/checkout@v4
      
      # Pushes the image to GitHub Container Registry
      - uses: mr-smithers-excellent/docker-build-push@v4
        name: Docker image
        with:
          dockerfile: Dockerfile
  